community/urls.py
from django.urls import path
from community import views

app_name = 'community'

urlpatterns = [
    # /write/
    path('write/', views.WriteFormView.as_view(), name='write'),
    # path('write/', write, name='write'),
    # /list/
    path('list/', views.ArticleListView.as_view(), name='list'),
    # path('list/', views.articleList, name='list'),
    # /view_detail/1/
    path('view_detail/<slug:pk>/', views.ArticleDetailView.as_view(), name='view_detail'),
    # path('view_detail/<int:num>/', views.viewDetail, name='view_detail'),
    # /change/
    path('change/', views.ArticleChangeView.as_view(), name='change_list'),
    # /view_detail/1/update
    path('<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
    # /view_detail/1/delete
    path('<int:pk>/delete', views.ArticleDeleteView.as_view(), name='article_delete'),

]

dashboard/urls.py
from django.urls import path
from dashboard.views import dashboard

app_name = 'dashboard'
urlpatterns = [
    path('', dashboard, name='dashboard'),
]

django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from community.views import index
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/',include('community.urls')),
    path('', index, name='index'),
    path('dashboard/', include('dashboard.urls')),
    # django.contrib.auth.urls 장고 내장 인증 urls 활용
    path('accounts/', include('django.contrib.auth.urls')),
    # 가입처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    # 계정생성이 완료됐다는 메시지를 보여줌
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'), 
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    {% block auth_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    {% endblock auth_css %}
    <title>
      {% block title %}
      WOOKIMODO HOMEPAGE
      {% endblock title %}
    </title>
  </head>
  
  <body>
    <!-- navbar -->
    {% include 'partials/navbar.html' %}
    
    <!-- contetns -->
    <div class="container" id="content">
      {% block content %}
      
      {% endblock content %}
    </div>
    <!-- footer -->
  {% include 'partials/footer.html' %}
</body>
</html>
<script src="{%static '/js/main.js'%}"></script> <!--모든곳에 다적용되기 때문에 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

{% block script %}

{% endblock script %}

templates/partials/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark fixed-bottom" >
  <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>

templates/partials/navbar.html
<div class="bg-light nav">
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/"><i class="bi bi-boxes" style="color: Green; font-size:25px;"></i>
                    WOOKIMODO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'community:list' %}">메모장</a>
                            {% comment %} 앱네임 : path 네임 {% endcomment %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard:dashboard' %}">대시보드</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Dropdown link
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">fhrmds</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/playdata.html">playdata</a>
                        </li>
                    </ul>
                </div>
                <!-- 로그인 인증 구간 -->
                <div class="collapse navbar-collapse justify-content-end">
                    <!-- bootstrap 오른쪽으로 움직임-->
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            {% if user.is_active %}
                            <!-- login 완료된 경우 -->
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                <i class="bi bi-box-arrow-in-right"></i>&nbsp;{{user.get_username}}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">비밀번호변경</a></li>
                            </ul>
                            {% else %}
                            <!-- login 안된경우 -->
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Anonymous
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'login' %}">로그인</a></li>
                                <li><a class="dropdown-item" href="{% url 'register' %}">회원가입</a></li>
                            </ul>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>

templates/partials/playdata.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>playdata</h1>
</body>
</html>