community/urls.py
from django.urls import path
from community import views

app_name = 'community'

urlpatterns = [
    # /write/
    path('write/', views.WriteFormView.as_view(), name='write'),
    # path('write/', write, name='write'),
    # /list/
    path('list/', views.ArticleListView.as_view(), name='list'),
    # path('list/', views.articleList, name='list'),
    # /view_detail/1/
    path('view_detail/<slug:pk>/', views.ArticleDetailView.as_view(), name='view_detail'),
    # path('view_detail/<int:num>/', views.viewDetail, name='view_detail'),
    # /change/
    path('change/', views.ArticleChangeView.as_view(), name='change_list'),
    # /view_detail/1/update
    path('<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
    # /view_detail/1/delete
    path('<int:pk>/delete', views.ArticleDeleteView.as_view(), name='article_delete'),

]

django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from community.views import index
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/',include('community.urls')),
    path('', index, name='index'),
    path('dashboard/', include('dashboard.urls')),
    # django.contrib.auth.urls 장고 내장 인증 urls 활용
    path('accounts/', include('django.contrib.auth.urls')),
    # 가입처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    # 계정생성이 완료됐다는 메시지를 보여줌
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'), 
]

community/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Article(models.Model):
  name = models.CharField(max_length=50)
  title = models.CharField(max_length=50)
  contents = models.TextField()
  url = models.URLField()
  email = models.EmailField()
  cdate = models.DateTimeField(auto_now_add = True)
  mdate = models.DateTimeField(auto_now=True)
  # User테이블과 연결.
  # on_delete=models.CASCADE -> user가 삭제되면 user의 글도 같이 삭제되게.
  # blank=True -> 작성자가 없는 글도 허용하겠다.
  owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

  
  class Meta:
    # 관리자 테이블의 title바꾸는 것.
    verbose_name_plural = "아티클 작성하기"
    # 수정한 날짜 기준으로 정렬. 최근 글이 위로 오게.
    ordering = ('-mdate',)
    
  def __str__(self):
    return f"{self.title} -- {self.name} -- {self.cdate}"
  
  # models.Model에 내장되어 있는 함수임.
  # 모델의 개별 데이터 rul을 문자열로 반환. 
  # args=(self.id,) -> id를 문자열로 반환. 원래 id는 int.
  def get_absolute_url(self):
    return reverse('community:view_detail', args=(self.id,))

community/forms.py
from django.forms import ModelForm
from community.models import Article
class Form(ModelForm):
  class Meta:
    model = Article
    fields = ['name', 'title', 'contents', 'url', 'email']

community/views.py
from django.shortcuts import render
from .forms import Form
from .models import Article
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django_tutorial.views import OwnerOnlyMixin



# Create your views here.
# def write(request):
#   # request의 post true이면
#   # 사용자가 입력한 form 데이터를 변수에 저장
#   # ORM으로 DB에 저장하기
#   if request.method == 'POST':
#     form = Form(request.POST)
#     if form.is_valid():
#       form.save() # 필드값 저장함.
#   else:
#     form = Form()
#   return render(request, 'community/write.html', {'form': form}) 
#   # 비즈니스 로직 구현
#   # data ={'키':'값'}
#   # return render(request, 'html템플릿 파일.html',data)

#   # return render(request, 'write.html', {'data': hello, 'data2':hello2})
# def articleList(request):
#   article_list = Article.objects.all()
#   return render(request, 'community/list.html', {'article_list': article_list})

# def viewDetail(request, num=1):
#   # 클릭한 레코드를 DB 읽어오기 
#   article_detail = Article.objects.get(id=num)
#   # article_detail = get_object_or_404(Article, id=num)
#   return render(request, 'community/view_detail.html', {'article_detail': article_detail})

def index(request):
  article_len = len(Article.objects.all())
  latest_article_list = Article.objects.all().order_by('cdate')[article_len-3:article_len]
  return render(request, 'index.html', {'latest_article_list': latest_article_list})

class WriteFormView(LoginRequiredMixin, CreateView):
  model = Article
  fields = ['name', 'title', 'contents', 'url', 'email']
  template_name = 'community/write.html'
  success_url = reverse_lazy('community:list')
  
  # 여기서의 form은 사용자가 입력한 form
  def form_valid(self, form):
    # 로그인되어 있는 user가 owner로 넘어가서 자동적으로 저장되기하기 위해서. user가 자기 id를 직접 입력하지는 않기 때문에.
    form.instance.owner = self.request.user
    return super().form_valid(form)
  
class ArticleListView(ListView):
  model = Article
  template_name = 'community/list.html'
  
class ArticleDetailView(DetailView):
  model = Article
  template_name = 'community/view_detail.html'
  
# 변경(login user 자료만 list_up)
class ArticleChangeView(LoginRequiredMixin, ListView):
  template_name = 'community/change_list.html'
  def get_queryset(self):
    return Article.objects.filter(owner=self.request.user)
  
# 로그인 user 메모 수정(Update) 
class ArticleUpdateView(OwnerOnlyMixin, UpdateView):
  model = Article
  template_name = 'community/article_update.html'
  fields = ['name', 'title', 'contents', 'url', 'email']
  success_url = reverse_lazy('community:change_list')
  
# 로그인 user 메모 삭제(Delete)
class ArticleDeleteView(OwnerOnlyMixin, DeleteView):
  model = Article
  template_name = 'community/article_delete.html'
  success_url = reverse_lazy('community:change_list')

community/templates/community/article_delete.html
{% extends "partials/base.html" %}
{% block title %}글 삭제 - {{ object.pk }}{% endblock %}
{% load crispy_forms_tags  %}
{% block content %}
  <h1>메모글 작성</h1>
  <p>by {{ user }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <p>{{ object }}를 정말 삭제 하겠습니까?</p>
    <input type="submit" value="삭제" class="btn btn-danger btn-sm">
  </form>
  
  {% endblock content %}

community/templates/community/article_update.html
{% extends "partials/base.html" %}
{% block title %}글 작성 - {{ user }}{% endblock %}
{% load crispy_forms_tags  %}
{% block content %}
  <h1>메모글 작성</h1>
  <p>by {{ user }}</p>

  <form action="" method="post">
    <table>
      {% csrf_token %}
      {{ form | crispy }}
    </table>
    <button type="submit" class="btn btn-success btn-block">글 수정</button>
  </form>
  
  {% endblock content %}

community/templates/community/change_list.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}수정 가능한 목록{% endblock %}

{% block part_style %}
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}
{% block content %}
  <h1>글 변경 목록 -{{ user }}</h1>
  <div class="article_box">
    <table class="table table-bodered table-condensed table-striped">
      <tr class="table-primary">
        <th>제목</th>
        <th>이름</th>
        <th>작성날짜</th>
        <th>수정</th>
        <th>삭제</th>
      </tr>
      {% for article in object_list %}
      <tr>
      <td><a href="{% url 'community:view_detail' article.id %}">{{ article.title }}</a></td>
      <td>{{ article.name }}</td>
      <td>{{ article.cdate|date:"Y년 M d일 D" }}</td>
      <td><a href="{% url 'community:article_update' article.id %}">수정</a></td>
      <td><a href="{% url 'community:article_delete' article.id %}">삭제</a></td>
      </tr>  
      {% endfor %}      
    </table>
  </div>
{% endblock content %}

community/templates/community/list.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}글작성 목록{% endblock %}

{% block part_style %}
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}
{% block content %}
  <div class="article_box">
    <p>
      <table>
        <tr>
          <th>제목</th>
          <th>이름</th>
          <th>작성 날짜</th>
          <th></th>
          <th></th>
        </tr>
        {% for article in object_list %}
        <tr>
          <td><a href="{% url 'community:view_detail' article.id %}">{{ article.title }}</a></td>
          <td>{{ article.name }}</td>
          <td>{{ article.cdate|date:"Y년 M d일 D" }}</td>
        </tr>
        {% endfor %}
      </table>
  </div>
  <p><a href="{% url 'community:change_list' %}">변경 가능 리스트</a>&nbsp;&nbsp;<a href="{% url 'community:write' %}">메모글 작성</a></p>
{% endblock content %}

community/templates/community/view_detail.html
{% extends "partials/base.html" %}
{% block title %}{{ object.pk }}번글 세부내용{% endblock %}

{% block content %}
<div>
  <table>
    <tr>
      <th>no</th>
      <td>{{ object.pk }}</td>
    </tr>
    <tr>
      <th>제목</th>
      <td>{{ object.title}}</td>
    </tr>
    <tr>
      <th>작성자</th>
      <td>{{ object.name}}</td>
    </tr>
    <tr>
      <th>내용</th>
      <td>{{ object.contents }}</td>
    </tr>
    <tr>
      <th></th>
      <td>{{ object.url }}/td>
    </tr>
    <tr>
      <th></th>
      <td>{{ object.email }}</td>
    </tr>
    <tr>
      <th></th>
      <td>{{ object.cdate }}</td>
    </tr>
  </table>
</div>
<div>
<br>
<button><a href="{% url 'community:article_update' object.id %}">수정</a></button>
<button><a href="{% url 'community:article_delete' object.id %}">삭제</a></button>

</div>
  {% endblock content %}

community/templates/community/write.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
메모 작성
{% endblock title %}
{% block content %}

<form action="" method="post">
  <table>
    {{ form | crispy}} {% csrf_token %}
  </table>
  <button type="submit">확인</button>
</form>

{% endblock content %}